// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OctaPro.Data;

#nullable disable

namespace OctaPro.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260308200357_InsertValuesToTableStatusPayment")]
    partial class InsertValuesToTableStatusPayment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<long>", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<long>", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("OctaPro.Models.Cache", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("key");

                    b.Property<int>("Expiration")
                        .HasColumnType("integer")
                        .HasColumnName("expiration");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Key")
                        .HasName("cache_pkey");

                    b.ToTable("cache", (string)null);
                });

            modelBuilder.Entity("OctaPro.Models.CacheLock", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("key");

                    b.Property<int>("Expiration")
                        .HasColumnType("integer")
                        .HasColumnName("expiration");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("owner");

                    b.HasKey("Key")
                        .HasName("cache_locks_pkey");

                    b.ToTable("cache_locks", (string)null);
                });

            modelBuilder.Entity("OctaPro.Models.Client", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("EntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("entity_id");

                    b.Property<long>("LawyerId")
                        .HasColumnType("bigint")
                        .HasColumnName("lawyer_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("clients_pkey");

                    b.HasIndex("EntityId");

                    b.HasIndex("LawyerId");

                    b.ToTable("clients", (string)null);
                });

            modelBuilder.Entity("OctaPro.Models.EntitiesRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("entities_roles_pkey");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("entities_roles_name_key");

                    b.ToTable("entities_roles", (string)null);
                });

            modelBuilder.Entity("OctaPro.Models.EntitiesRolesMap", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("assigned_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long?>("AssignedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("assigned_by");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("EntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("entity_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("entities_roles_map_pkey");

                    b.HasIndex("RoleId");

                    b.HasIndex("EntityId", "RoleId")
                        .IsUnique()
                        .HasDatabaseName("unique_entity_role");

                    b.ToTable("entities_roles_map", (string)null);
                });

            modelBuilder.Entity("OctaPro.Models.Entity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .HasColumnName("entity_type")
                        .IsFixedLength();

                    b.Property<Guid>("IdPublic")
                        .HasColumnType("uuid")
                        .HasColumnName("id_public");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer")
                        .HasColumnName("status_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("entities_pkey");

                    b.HasIndex("IdPublic")
                        .IsUnique()
                        .HasDatabaseName("entities_id_public_key");

                    b.ToTable("entities", (string)null);
                });

            modelBuilder.Entity("OctaPro.Models.EntityCompany", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Cnpj")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cnpj");

                    b.Property<string>("CorporateEmail")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("CorporateMobile")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("mobile");

                    b.Property<string>("CorporateName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("corporate_name");

                    b.Property<string>("CorporatePhone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("EntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("entity_id");

                    b.Property<string>("TradeName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("trade_name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("entities_company_pkey");

                    b.HasIndex("EntityId")
                        .IsUnique();

                    b.ToTable("entities_company", (string)null);
                });

            modelBuilder.Entity("OctaPro.Models.EntityIndividual", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("address");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<string>("Cpf")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("cpf");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<long>("EntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("entity_id");

                    b.Property<string>("Mobile")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("mobile");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone");

                    b.Property<string>("Rg")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("rg");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("entities_individual_pkey");

                    b.HasIndex("EntityId")
                        .IsUnique();

                    b.ToTable("entities_individual", (string)null);
                });

            modelBuilder.Entity("OctaPro.Models.Job", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<short>("Attempts")
                        .HasColumnType("smallint")
                        .HasColumnName("attempts");

                    b.Property<int>("AvailableAt")
                        .HasColumnType("integer")
                        .HasColumnName("available_at");

                    b.Property<int>("CreatedAt")
                        .HasColumnType("integer")
                        .HasColumnName("created_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<string>("Queue")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("queue");

                    b.Property<int?>("ReservedAt")
                        .HasColumnType("integer")
                        .HasColumnName("reserved_at");

                    b.HasKey("Id")
                        .HasName("jobs_pkey");

                    b.HasIndex("Queue")
                        .HasDatabaseName("jobs_queue_index");

                    b.ToTable("jobs", (string)null);
                });

            modelBuilder.Entity("OctaPro.Models.JobBatch", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("id");

                    b.Property<int?>("CancelledAt")
                        .HasColumnType("integer")
                        .HasColumnName("cancelled_at");

                    b.Property<int>("CreatedAt")
                        .HasColumnType("integer")
                        .HasColumnName("created_at");

                    b.Property<string>("FailedJobIds")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("failed_job_ids");

                    b.Property<int>("FailedJobs")
                        .HasColumnType("integer")
                        .HasColumnName("failed_jobs");

                    b.Property<int?>("FinishedAt")
                        .HasColumnType("integer")
                        .HasColumnName("finished_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Options")
                        .HasColumnType("text")
                        .HasColumnName("options");

                    b.Property<int>("PendingJobs")
                        .HasColumnType("integer")
                        .HasColumnName("pending_jobs");

                    b.Property<int>("TotalJobs")
                        .HasColumnType("integer")
                        .HasColumnName("total_jobs");

                    b.HasKey("Id")
                        .HasName("job_batches_pkey");

                    b.ToTable("job_batches", (string)null);
                });

            modelBuilder.Entity("OctaPro.Models.JudicialAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("judicial_action");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("NatureActionId")
                        .HasColumnType("integer")
                        .HasColumnName("nature_action_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("judicials_actions_pkey");

                    b.HasIndex("NatureActionId");

                    b.ToTable("judicials_actions", (string)null);
                });

            modelBuilder.Entity("OctaPro.Models.JudicialProcess", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<Guid>("IdPublic")
                        .HasColumnType("uuid")
                        .HasColumnName("id_public");

                    b.Property<DateOnly>("InitialDate")
                        .HasColumnType("date")
                        .HasColumnName("initial_date");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_archived");

                    b.Property<int>("JudicialActionId")
                        .HasColumnType("integer")
                        .HasColumnName("judicial_action_id");

                    b.Property<int>("NatureActionId")
                        .HasColumnType("integer")
                        .HasColumnName("nature_action_id");

                    b.Property<string>("ProcessNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("process_number");

                    b.Property<string>("Respondent")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("respondent");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("judicial_processes_pkey");

                    b.HasIndex("IdPublic")
                        .IsUnique()
                        .HasDatabaseName("judicial_processes_id_public_key");

                    b.HasIndex("JudicialActionId");

                    b.HasIndex("NatureActionId");

                    b.HasIndex("ProcessNumber")
                        .IsUnique()
                        .HasDatabaseName("unique_process_number");

                    b.HasIndex("UserId");

                    b.ToTable("judicial_processes", (string)null);
                });

            modelBuilder.Entity("OctaPro.Models.JudicialProcessEntity", b =>
                {
                    b.Property<long>("JudicialProcessId")
                        .HasColumnType("bigint")
                        .HasColumnName("judicial_process_id");

                    b.Property<long>("EntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("entity_id");

                    b.HasKey("JudicialProcessId", "EntityId");

                    b.HasIndex("EntityId");

                    b.ToTable("judicial_process_entity", (string)null);
                });

            modelBuilder.Entity("OctaPro.Models.JudicialProcessUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AccessLevel")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("access_level")
                        .HasDefaultValueSql("'private'::character varying");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("JudicialProcessId")
                        .HasColumnType("bigint")
                        .HasColumnName("judicial_process_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("judicial_process_user_pkey");

                    b.HasIndex("UserId");

                    b.HasIndex("JudicialProcessId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("unique_process_user");

                    b.ToTable("judicial_process_user", (string)null);
                });

            modelBuilder.Entity("OctaPro.Models.LegalFee", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasDefaultValue(0.0m)
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("IdPublic")
                        .HasColumnType("uuid")
                        .HasColumnName("id_public");

                    b.Property<long>("JudicialProcessId")
                        .HasColumnType("bigint")
                        .HasColumnName("judicial_process_id");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("note");

                    b.Property<int>("QuantityInstallment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("quantity_installment");

                    b.Property<int>("StatusPaymentId")
                        .HasColumnType("integer")
                        .HasColumnName("status_payment_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("legal_fees_pkey");

                    b.HasIndex("IdPublic")
                        .IsUnique()
                        .HasDatabaseName("legal_fees_id_public_key");

                    b.HasIndex("JudicialProcessId");

                    b.HasIndex("StatusPaymentId");

                    b.HasIndex("UserId");

                    b.ToTable("legal_fees", (string)null);
                });

            modelBuilder.Entity("OctaPro.Models.LegalFeeEntity", b =>
                {
                    b.Property<long>("LegalFeeId")
                        .HasColumnType("bigint")
                        .HasColumnName("legal_fee_id");

                    b.Property<long>("EntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("entity_id");

                    b.HasKey("LegalFeeId", "EntityId");

                    b.HasIndex("EntityId");

                    b.ToTable("legal_fee_entity", (string)null);
                });

            modelBuilder.Entity("OctaPro.Models.LegalFeesInstallment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CurrentInstallment")
                        .HasColumnType("integer")
                        .HasColumnName("current_installment");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<long>("EntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("entity_id");

                    b.Property<Guid>("IdPublic")
                        .HasColumnType("uuid")
                        .HasColumnName("id_public");

                    b.Property<int>("LegalFeeId")
                        .HasColumnType("integer")
                        .HasColumnName("legal_fee_id");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("note");

                    b.Property<DateOnly?>("PaymentDate")
                        .HasColumnType("date")
                        .HasColumnName("payment_date");

                    b.Property<int>("StatusPaymentId")
                        .HasColumnType("integer")
                        .HasColumnName("status_payment_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("ValueInstallment")
                        .HasColumnType("numeric")
                        .HasColumnName("value_installment");

                    b.HasKey("Id")
                        .HasName("installments_legal_fees_pkey");

                    b.HasIndex("EntityId");

                    b.HasIndex("IdPublic")
                        .IsUnique()
                        .HasDatabaseName("installments_legal_fees_id_public_key");

                    b.HasIndex("StatusPaymentId");

                    b.ToTable("legal_fees_installments", (string)null);
                });

            modelBuilder.Entity("OctaPro.Models.Migration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Batch")
                        .HasColumnType("integer")
                        .HasColumnName("batch");

                    b.Property<string>("Migration1")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("migration");

                    b.HasKey("Id")
                        .HasName("migrations_pkey");

                    b.ToTable("migrations", (string)null);
                });

            modelBuilder.Entity("OctaPro.Models.NatureAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Nature")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nature");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("nature_actions_pkey");

                    b.ToTable("nature_actions", (string)null);
                });

            modelBuilder.Entity("OctaPro.Models.Session", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("id");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<int>("LastActivity")
                        .HasColumnType("integer")
                        .HasColumnName("last_activity");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("sessions_pkey");

                    b.HasIndex("LastActivity")
                        .HasDatabaseName("sessions_last_activity_index");

                    b.HasIndex("UserId")
                        .HasDatabaseName("sessions_user_id_index");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("OctaPro.Models.Settlement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("amount");

                    b.Property<string>("Competence")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("competence");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CurrentInstallment")
                        .HasColumnType("integer")
                        .HasColumnName("current_installment");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<Guid>("IdPublic")
                        .HasColumnType("uuid")
                        .HasColumnName("id_public");

                    b.Property<long>("JudicialProcessId")
                        .HasColumnType("bigint")
                        .HasColumnName("judicial_process_id");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("note");

                    b.Property<DateOnly?>("PaymentDate")
                        .HasColumnType("date")
                        .HasColumnName("payment_date");

                    b.Property<int>("QuantityInstallment")
                        .HasColumnType("integer")
                        .HasColumnName("quantity_installment");

                    b.Property<int>("StatusPaymentId")
                        .HasColumnType("integer")
                        .HasColumnName("status_payment_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<decimal?>("ValueInstallment")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("value_installment")
                        .HasComputedColumnSql("(amount / (NULLIF(quantity_installment, 0))::numeric)", true);

                    b.HasKey("Id")
                        .HasName("installments_settlement_pkey");

                    b.HasIndex("IdPublic")
                        .IsUnique()
                        .HasDatabaseName("settlement_id_public_key");

                    b.HasIndex("JudicialProcessId");

                    b.HasIndex("StatusPaymentId");

                    b.HasIndex("UserId");

                    b.ToTable("settlement", (string)null);
                });

            modelBuilder.Entity("OctaPro.Models.StatusEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("description");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("status_entities_pkey");

                    b.ToTable("status_entities", (string)null);
                });

            modelBuilder.Entity("OctaPro.Models.StatusPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("description");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("status_payment_pkey");

                    b.ToTable("status_payment", (string)null);
                });

            modelBuilder.Entity("OctaPro.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<Guid>("IdPublic")
                        .HasColumnType("uuid")
                        .HasColumnName("id_public");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("ProfilePhotoPath")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("profile_photo_path");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id")
                        .HasName("users_pkey");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("users_email_unique");

                    b.HasIndex("IdPublic")
                        .IsUnique()
                        .HasDatabaseName("users_id_public_key");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<long>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.HasOne("OctaPro.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.HasOne("OctaPro.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<long>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<long>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OctaPro.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.HasOne("OctaPro.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OctaPro.Models.Client", b =>
                {
                    b.HasOne("OctaPro.Models.Entity", "Entity")
                        .WithMany()
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OctaPro.Models.User", "Lawyer")
                        .WithMany("Clients")
                        .HasForeignKey("LawyerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_client_lawyer");

                    b.Navigation("Entity");

                    b.Navigation("Lawyer");
                });

            modelBuilder.Entity("OctaPro.Models.EntitiesRolesMap", b =>
                {
                    b.HasOne("OctaPro.Models.Entity", "Entity")
                        .WithMany()
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OctaPro.Models.EntitiesRole", "Role")
                        .WithMany("EntitiesRolesMaps")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_entities_roles_map");

                    b.Navigation("Entity");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("OctaPro.Models.EntityCompany", b =>
                {
                    b.HasOne("OctaPro.Models.Entity", "Entity")
                        .WithOne("EntityCompany")
                        .HasForeignKey("OctaPro.Models.EntityCompany", "EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_entity_company");

                    b.Navigation("Entity");
                });

            modelBuilder.Entity("OctaPro.Models.EntityIndividual", b =>
                {
                    b.HasOne("OctaPro.Models.Entity", "Entity")
                        .WithOne("EntityIndividual")
                        .HasForeignKey("OctaPro.Models.EntityIndividual", "EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_entity_individual");

                    b.Navigation("Entity");
                });

            modelBuilder.Entity("OctaPro.Models.JudicialAction", b =>
                {
                    b.HasOne("OctaPro.Models.NatureAction", "NatureAction")
                        .WithMany("JudicialAction")
                        .HasForeignKey("NatureActionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_nature_action");

                    b.Navigation("NatureAction");
                });

            modelBuilder.Entity("OctaPro.Models.JudicialProcess", b =>
                {
                    b.HasOne("OctaPro.Models.JudicialAction", "JudicialAction")
                        .WithMany()
                        .HasForeignKey("JudicialActionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OctaPro.Models.NatureAction", "NatureAction")
                        .WithMany("JudicialProcesses")
                        .HasForeignKey("NatureActionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_nature_action");

                    b.HasOne("OctaPro.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JudicialAction");

                    b.Navigation("NatureAction");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OctaPro.Models.JudicialProcessEntity", b =>
                {
                    b.HasOne("OctaPro.Models.Entity", "Entity")
                        .WithMany("JudicialProcessEntities")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_judicial_process_entity_entity");

                    b.HasOne("OctaPro.Models.JudicialProcess", "JudicialProcess")
                        .WithMany("JudicialProcessEntities")
                        .HasForeignKey("JudicialProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_judicial_process_entity_process");

                    b.Navigation("Entity");

                    b.Navigation("JudicialProcess");
                });

            modelBuilder.Entity("OctaPro.Models.JudicialProcessUser", b =>
                {
                    b.HasOne("OctaPro.Models.JudicialProcess", "JudicialProcess")
                        .WithMany()
                        .HasForeignKey("JudicialProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OctaPro.Models.User", "User")
                        .WithMany("JudicialProcessUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user");

                    b.Navigation("JudicialProcess");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OctaPro.Models.LegalFee", b =>
                {
                    b.HasOne("OctaPro.Models.JudicialProcess", "JudicialProcess")
                        .WithMany("LegalFees")
                        .HasForeignKey("JudicialProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_judicial_process");

                    b.HasOne("OctaPro.Models.StatusPayment", "StatusPayment")
                        .WithMany("LegalFees")
                        .HasForeignKey("StatusPaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_status_payment");

                    b.HasOne("OctaPro.Models.User", "User")
                        .WithMany("LegalFees")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_id");

                    b.Navigation("JudicialProcess");

                    b.Navigation("StatusPayment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OctaPro.Models.LegalFeeEntity", b =>
                {
                    b.HasOne("OctaPro.Models.Entity", "Entity")
                        .WithMany("LegalFeeEntities")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_legal_fee_entity_entity");

                    b.HasOne("OctaPro.Models.LegalFee", "LegalFee")
                        .WithMany("LegalFeeEntities")
                        .HasForeignKey("LegalFeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_legal_fee_entity_legal_fee");

                    b.Navigation("Entity");

                    b.Navigation("LegalFee");
                });

            modelBuilder.Entity("OctaPro.Models.LegalFeesInstallment", b =>
                {
                    b.HasOne("OctaPro.Models.Entity", "Entity")
                        .WithMany("LegalFeesInstallments")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_legal_fee_entity");

                    b.HasOne("OctaPro.Models.StatusPayment", "StatusPayment")
                        .WithMany("LegalFeesInstallments")
                        .HasForeignKey("StatusPaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_status_payment");

                    b.Navigation("Entity");

                    b.Navigation("StatusPayment");
                });

            modelBuilder.Entity("OctaPro.Models.Settlement", b =>
                {
                    b.HasOne("OctaPro.Models.JudicialProcess", "JudicialProcess")
                        .WithMany("Settlements")
                        .HasForeignKey("JudicialProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_judicial_process");

                    b.HasOne("OctaPro.Models.StatusPayment", "StatusPayment")
                        .WithMany("Settlements")
                        .HasForeignKey("StatusPaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_status_payment");

                    b.HasOne("OctaPro.Models.User", "User")
                        .WithMany("Settlements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_id");

                    b.Navigation("JudicialProcess");

                    b.Navigation("StatusPayment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OctaPro.Models.EntitiesRole", b =>
                {
                    b.Navigation("EntitiesRolesMaps");
                });

            modelBuilder.Entity("OctaPro.Models.Entity", b =>
                {
                    b.Navigation("EntityCompany");

                    b.Navigation("EntityIndividual");

                    b.Navigation("JudicialProcessEntities");

                    b.Navigation("LegalFeeEntities");

                    b.Navigation("LegalFeesInstallments");
                });

            modelBuilder.Entity("OctaPro.Models.JudicialProcess", b =>
                {
                    b.Navigation("JudicialProcessEntities");

                    b.Navigation("LegalFees");

                    b.Navigation("Settlements");
                });

            modelBuilder.Entity("OctaPro.Models.LegalFee", b =>
                {
                    b.Navigation("LegalFeeEntities");
                });

            modelBuilder.Entity("OctaPro.Models.NatureAction", b =>
                {
                    b.Navigation("JudicialAction");

                    b.Navigation("JudicialProcesses");
                });

            modelBuilder.Entity("OctaPro.Models.StatusPayment", b =>
                {
                    b.Navigation("LegalFees");

                    b.Navigation("LegalFeesInstallments");

                    b.Navigation("Settlements");
                });

            modelBuilder.Entity("OctaPro.Models.User", b =>
                {
                    b.Navigation("Clients");

                    b.Navigation("JudicialProcessUsers");

                    b.Navigation("LegalFees");

                    b.Navigation("Settlements");
                });
#pragma warning restore 612, 618
        }
    }
}
