// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using processum.Data;

#nullable disable

namespace processum.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260127020703_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UserRole", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("user_roles_pkey");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("processum.Models.Cache", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("key");

                    b.Property<int>("Expiration")
                        .HasColumnType("integer")
                        .HasColumnName("expiration");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Key")
                        .HasName("cache_pkey");

                    b.ToTable("cache", (string)null);
                });

            modelBuilder.Entity("processum.Models.CacheLock", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("key");

                    b.Property<int>("Expiration")
                        .HasColumnType("integer")
                        .HasColumnName("expiration");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("owner");

                    b.HasKey("Key")
                        .HasName("cache_locks_pkey");

                    b.ToTable("cache_locks", (string)null);
                });

            modelBuilder.Entity("processum.Models.Client", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("EntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("entity_id");

                    b.Property<long>("LawyerId")
                        .HasColumnType("bigint")
                        .HasColumnName("lawyer_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("clients_pkey");

                    b.HasIndex("EntityId");

                    b.HasIndex("LawyerId");

                    b.ToTable("clients", (string)null);
                });

            modelBuilder.Entity("processum.Models.EntitiesRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("entities_roles_pkey");

                    b.HasIndex(new[] { "Name" }, "entities_roles_name_key")
                        .IsUnique();

                    b.ToTable("entities_roles", (string)null);
                });

            modelBuilder.Entity("processum.Models.EntitiesRolesMap", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long?>("AssignedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("assigned_by");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("EntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("entity_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("entities_roles_map_pkey");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "EntityId", "RoleId" }, "unique_entity_role")
                        .IsUnique();

                    b.ToTable("entities_roles_map", (string)null);
                });

            modelBuilder.Entity("processum.Models.Entity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .HasColumnName("entity_type")
                        .IsFixedLength();

                    b.Property<Guid>("IdPublic")
                        .HasColumnType("uuid")
                        .HasColumnName("id_public");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer")
                        .HasColumnName("status_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("entities_pkey");

                    b.HasIndex(new[] { "IdPublic" }, "entities_id_public_key")
                        .IsUnique();

                    b.ToTable("entities", (string)null);
                });

            modelBuilder.Entity("processum.Models.EntityCompany", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Cnpj")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cnpj");

                    b.Property<string>("CorporateEmail")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("CorporateMobile")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("mobile");

                    b.Property<string>("CorporateName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("corporate_name");

                    b.Property<string>("CorporatePhone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("EntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("entity_id");

                    b.Property<string>("TradeName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("trade_name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("entities_company_pkey");

                    b.HasIndex("EntityId")
                        .IsUnique();

                    b.ToTable("entities_company", (string)null);
                });

            modelBuilder.Entity("processum.Models.EntityIndividual", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("address");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<string>("Cpf")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("cpf");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<long>("EntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("entity_id");

                    b.Property<string>("Mobile")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("mobile");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone");

                    b.Property<string>("Rg")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("rg");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("entities_individual_pkey");

                    b.HasIndex("EntityId")
                        .IsUnique();

                    b.ToTable("entities_individual", (string)null);
                });

            modelBuilder.Entity("processum.Models.FailedJob", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Connection")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("connection");

                    b.Property<string>("Exception")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("exception");

                    b.Property<DateTime>("FailedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp(0) without time zone")
                        .HasColumnName("failed_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<string>("Queue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("queue");

                    b.Property<string>("Uuid")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("uuid");

                    b.HasKey("Id")
                        .HasName("failed_jobs_pkey");

                    b.HasIndex(new[] { "Uuid" }, "failed_jobs_uuid_unique")
                        .IsUnique();

                    b.ToTable("failed_jobs", (string)null);
                });

            modelBuilder.Entity("processum.Models.Job", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<short>("Attempts")
                        .HasColumnType("smallint")
                        .HasColumnName("attempts");

                    b.Property<int>("AvailableAt")
                        .HasColumnType("integer")
                        .HasColumnName("available_at");

                    b.Property<int>("CreatedAt")
                        .HasColumnType("integer")
                        .HasColumnName("created_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<string>("Queue")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("queue");

                    b.Property<int?>("ReservedAt")
                        .HasColumnType("integer")
                        .HasColumnName("reserved_at");

                    b.HasKey("Id")
                        .HasName("jobs_pkey");

                    b.HasIndex(new[] { "Queue" }, "jobs_queue_index");

                    b.ToTable("jobs", (string)null);
                });

            modelBuilder.Entity("processum.Models.JobBatch", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("id");

                    b.Property<int?>("CancelledAt")
                        .HasColumnType("integer")
                        .HasColumnName("cancelled_at");

                    b.Property<int>("CreatedAt")
                        .HasColumnType("integer")
                        .HasColumnName("created_at");

                    b.Property<string>("FailedJobIds")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("failed_job_ids");

                    b.Property<int>("FailedJobs")
                        .HasColumnType("integer")
                        .HasColumnName("failed_jobs");

                    b.Property<int?>("FinishedAt")
                        .HasColumnType("integer")
                        .HasColumnName("finished_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Options")
                        .HasColumnType("text")
                        .HasColumnName("options");

                    b.Property<int>("PendingJobs")
                        .HasColumnType("integer")
                        .HasColumnName("pending_jobs");

                    b.Property<int>("TotalJobs")
                        .HasColumnType("integer")
                        .HasColumnName("total_jobs");

                    b.HasKey("Id")
                        .HasName("job_batches_pkey");

                    b.ToTable("job_batches", (string)null);
                });

            modelBuilder.Entity("processum.Models.JudicialAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("judicial_action");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("NatureActionId")
                        .HasColumnType("integer")
                        .HasColumnName("nature_action_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("judicials_actions_pkey");

                    b.HasIndex("NatureActionId");

                    b.ToTable("judicials_actions", (string)null);
                });

            modelBuilder.Entity("processum.Models.JudicialProcess", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<Guid>("IdPublic")
                        .HasColumnType("uuid")
                        .HasColumnName("id_public");

                    b.Property<DateOnly>("InitialDate")
                        .HasColumnType("date")
                        .HasColumnName("initial_date");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_archived");

                    b.Property<int>("JudicialActionId")
                        .HasColumnType("integer")
                        .HasColumnName("judicial_action_id");

                    b.Property<int>("NatureActionId")
                        .HasColumnType("integer")
                        .HasColumnName("nature_action_id");

                    b.Property<string>("ProcessNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("process_number");

                    b.Property<string>("Respondent")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("respondent");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("judicial_processes_pkey");

                    b.HasIndex("JudicialActionId");

                    b.HasIndex("NatureActionId");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "IdPublic" }, "judicial_processes_id_public_key")
                        .IsUnique();

                    b.HasIndex(new[] { "ProcessNumber" }, "unique_process_number")
                        .IsUnique();

                    b.ToTable("judicial_processes", (string)null);
                });

            modelBuilder.Entity("processum.Models.JudicialProcessEntity", b =>
                {
                    b.Property<long>("JudicialProcessId")
                        .HasColumnType("bigint")
                        .HasColumnName("judicial_process_id");

                    b.Property<long>("EntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("entity_id");

                    b.HasKey("JudicialProcessId", "EntityId");

                    b.HasIndex("EntityId");

                    b.ToTable("judicial_process_entity", (string)null);
                });

            modelBuilder.Entity("processum.Models.JudicialProcessUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AccessLevel")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("access_level")
                        .HasDefaultValueSql("'private'::character varying");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("JudicialProcessId")
                        .HasColumnType("bigint")
                        .HasColumnName("judicial_process_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("judicial_process_user_pkey");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "JudicialProcessId", "UserId" }, "unique_process_user")
                        .IsUnique();

                    b.ToTable("judicial_process_user", (string)null);
                });

            modelBuilder.Entity("processum.Models.LegalFee", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasDefaultValue(0.0m)
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("IdPublic")
                        .HasColumnType("uuid")
                        .HasColumnName("id_public");

                    b.Property<long>("JudicialProcessId")
                        .HasColumnType("bigint")
                        .HasColumnName("judicial_process_id");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("note");

                    b.Property<int>("QuantityInstallment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("quantity_installment");

                    b.Property<int>("StatusPaymentId")
                        .HasColumnType("integer")
                        .HasColumnName("status_payment_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("legal_fees_pkey");

                    b.HasIndex("JudicialProcessId");

                    b.HasIndex("StatusPaymentId");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "IdPublic" }, "legal_fees_id_public_key")
                        .IsUnique();

                    b.ToTable("legal_fees", (string)null);
                });

            modelBuilder.Entity("processum.Models.LegalFeeEntity", b =>
                {
                    b.Property<long>("LegalFeeId")
                        .HasColumnType("bigint")
                        .HasColumnName("legal_fee_id");

                    b.Property<long>("EntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("entity_id");

                    b.HasKey("LegalFeeId", "EntityId");

                    b.HasIndex("EntityId");

                    b.ToTable("legal_fee_entity", (string)null);
                });

            modelBuilder.Entity("processum.Models.LegalFeesInstallment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CurrentInstallment")
                        .HasColumnType("integer")
                        .HasColumnName("current_installment");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<long>("EntityId")
                        .HasColumnType("bigint")
                        .HasColumnName("entity_id");

                    b.Property<Guid>("IdPublic")
                        .HasColumnType("uuid")
                        .HasColumnName("id_public");

                    b.Property<int>("LegalFeeId")
                        .HasColumnType("integer")
                        .HasColumnName("legal_fee_id");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("note");

                    b.Property<DateOnly?>("PaymentDate")
                        .HasColumnType("date")
                        .HasColumnName("payment_date");

                    b.Property<int>("StatusPaymentId")
                        .HasColumnType("integer")
                        .HasColumnName("status_payment_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("ValueInstallment")
                        .HasColumnType("numeric")
                        .HasColumnName("value_installment");

                    b.HasKey("Id")
                        .HasName("installments_legal_fees_pkey");

                    b.HasIndex("EntityId");

                    b.HasIndex("StatusPaymentId");

                    b.HasIndex(new[] { "IdPublic" }, "installments_legal_fees_id_public_key")
                        .IsUnique();

                    b.ToTable("legal_fees_installments", (string)null);
                });

            modelBuilder.Entity("processum.Models.Migration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Batch")
                        .HasColumnType("integer")
                        .HasColumnName("batch");

                    b.Property<string>("Migration1")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("migration");

                    b.HasKey("Id")
                        .HasName("migrations_pkey");

                    b.ToTable("migrations", (string)null);
                });

            modelBuilder.Entity("processum.Models.NatureAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Nature")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nature");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("nature_actions_pkey");

                    b.ToTable("nature_actions", (string)null);
                });

            modelBuilder.Entity("processum.Models.PasswordResetToken", b =>
                {
                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp(0) without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("token");

                    b.HasKey("Email")
                        .HasName("password_reset_tokens_pkey");

                    b.ToTable("password_reset_tokens", (string)null);
                });

            modelBuilder.Entity("processum.Models.PersonalAccessToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Abilities")
                        .HasColumnType("text")
                        .HasColumnName("abilities");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp(0) without time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp(0) without time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp(0) without time zone")
                        .HasColumnName("last_used_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token");

                    b.Property<long>("TokenableId")
                        .HasColumnType("bigint")
                        .HasColumnName("tokenable_id");

                    b.Property<string>("TokenableType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("tokenable_type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp(0) without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("personal_access_tokens_pkey");

                    b.HasIndex(new[] { "ExpiresAt" }, "personal_access_tokens_expires_at_index");

                    b.HasIndex(new[] { "Token" }, "personal_access_tokens_token_unique")
                        .IsUnique();

                    b.HasIndex(new[] { "TokenableType", "TokenableId" }, "personal_access_tokens_tokenable_type_tokenable_id_index");

                    b.ToTable("personal_access_tokens", (string)null);
                });

            modelBuilder.Entity("processum.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Role1")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("roles_pkey");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("processum.Models.Session", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("id");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<int>("LastActivity")
                        .HasColumnType("integer")
                        .HasColumnName("last_activity");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("sessions_pkey");

                    b.HasIndex(new[] { "LastActivity" }, "sessions_last_activity_index");

                    b.HasIndex(new[] { "UserId" }, "sessions_user_id_index");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("processum.Models.Settlement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("amount");

                    b.Property<string>("Competence")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("competence");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CurrentInstallment")
                        .HasColumnType("integer")
                        .HasColumnName("current_installment");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<Guid>("IdPublic")
                        .HasColumnType("uuid")
                        .HasColumnName("id_public");

                    b.Property<long>("JudicialProcessId")
                        .HasColumnType("bigint")
                        .HasColumnName("judicial_process_id");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("note");

                    b.Property<DateOnly?>("PaymentDate")
                        .HasColumnType("date")
                        .HasColumnName("payment_date");

                    b.Property<int>("QuantityInstallment")
                        .HasColumnType("integer")
                        .HasColumnName("quantity_installment");

                    b.Property<int>("StatusPaymentId")
                        .HasColumnType("integer")
                        .HasColumnName("status_payment_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<decimal?>("ValueInstallment")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("value_installment")
                        .HasComputedColumnSql("(amount / (NULLIF(quantity_installment, 0))::numeric)", true);

                    b.HasKey("Id")
                        .HasName("installments_settlement_pkey");

                    b.HasIndex("JudicialProcessId");

                    b.HasIndex("StatusPaymentId");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "IdPublic" }, "settlement_id_public_key")
                        .IsUnique();

                    b.ToTable("settlement", (string)null);
                });

            modelBuilder.Entity("processum.Models.StatusEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("description");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("status_entities_pkey");

                    b.ToTable("status_entities", (string)null);
                });

            modelBuilder.Entity("processum.Models.StatusPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("description");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("status_payment_pkey");

                    b.ToTable("status_payment", (string)null);
                });

            modelBuilder.Entity("processum.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp(0) without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("EmailVerifiedAt")
                        .HasColumnType("timestamp(0) without time zone")
                        .HasColumnName("email_verified_at");

                    b.Property<Guid>("IdPublic")
                        .HasColumnType("uuid")
                        .HasColumnName("id_public");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password");

                    b.Property<string>("ProfilePhotoPath")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("profile_photo_path");

                    b.Property<string>("RememberToken")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("remember_token");

                    b.Property<DateTime?>("TwoFactorConfirmedAt")
                        .HasColumnType("timestamp(0) without time zone")
                        .HasColumnName("two_factor_confirmed_at");

                    b.Property<string>("TwoFactorRecoveryCodes")
                        .HasColumnType("text")
                        .HasColumnName("two_factor_recovery_codes");

                    b.Property<string>("TwoFactorSecret")
                        .HasColumnType("text")
                        .HasColumnName("two_factor_secret");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp(0) without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("users_pkey");

                    b.HasIndex(new[] { "Email" }, "users_email_unique")
                        .IsUnique();

                    b.HasIndex(new[] { "IdPublic" }, "users_id_public_key")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("UserRole", b =>
                {
                    b.HasOne("processum.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role");

                    b.HasOne("processum.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user");
                });

            modelBuilder.Entity("processum.Models.Client", b =>
                {
                    b.HasOne("processum.Models.Entity", "Entity")
                        .WithMany()
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("processum.Models.User", "Lawyer")
                        .WithMany("Clients")
                        .HasForeignKey("LawyerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_client_lawyer");

                    b.Navigation("Entity");

                    b.Navigation("Lawyer");
                });

            modelBuilder.Entity("processum.Models.EntitiesRolesMap", b =>
                {
                    b.HasOne("processum.Models.Entity", "Entity")
                        .WithMany()
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("processum.Models.EntitiesRole", "Role")
                        .WithMany("EntitiesRolesMaps")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_entities_roles_map");

                    b.Navigation("Entity");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("processum.Models.EntityCompany", b =>
                {
                    b.HasOne("processum.Models.Entity", "Entity")
                        .WithOne("EntityCompany")
                        .HasForeignKey("processum.Models.EntityCompany", "EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_entity_company");

                    b.Navigation("Entity");
                });

            modelBuilder.Entity("processum.Models.EntityIndividual", b =>
                {
                    b.HasOne("processum.Models.Entity", "Entity")
                        .WithOne("EntityIndividual")
                        .HasForeignKey("processum.Models.EntityIndividual", "EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_entity_individual");

                    b.Navigation("Entity");
                });

            modelBuilder.Entity("processum.Models.JudicialAction", b =>
                {
                    b.HasOne("processum.Models.NatureAction", "NatureAction")
                        .WithMany("JudicialAction")
                        .HasForeignKey("NatureActionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_nature_action");

                    b.Navigation("NatureAction");
                });

            modelBuilder.Entity("processum.Models.JudicialProcess", b =>
                {
                    b.HasOne("processum.Models.JudicialAction", "JudicialAction")
                        .WithMany()
                        .HasForeignKey("JudicialActionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("processum.Models.NatureAction", "NatureAction")
                        .WithMany("JudicialProcesses")
                        .HasForeignKey("NatureActionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_nature_action");

                    b.HasOne("processum.Models.User", "User")
                        .WithMany("JudicialProcesses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_id");

                    b.Navigation("JudicialAction");

                    b.Navigation("NatureAction");

                    b.Navigation("User");
                });

            modelBuilder.Entity("processum.Models.JudicialProcessEntity", b =>
                {
                    b.HasOne("processum.Models.Entity", "Entity")
                        .WithMany("JudicialProcessEntities")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_judicial_process_entity_entity");

                    b.HasOne("processum.Models.JudicialProcess", "JudicialProcess")
                        .WithMany("JudicialProcessEntities")
                        .HasForeignKey("JudicialProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_judicial_process_entity_process");

                    b.Navigation("Entity");

                    b.Navigation("JudicialProcess");
                });

            modelBuilder.Entity("processum.Models.JudicialProcessUser", b =>
                {
                    b.HasOne("processum.Models.JudicialProcess", "JudicialProcess")
                        .WithMany()
                        .HasForeignKey("JudicialProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("processum.Models.User", "User")
                        .WithMany("JudicialProcessUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user");

                    b.Navigation("JudicialProcess");

                    b.Navigation("User");
                });

            modelBuilder.Entity("processum.Models.LegalFee", b =>
                {
                    b.HasOne("processum.Models.JudicialProcess", "JudicialProcess")
                        .WithMany("LegalFees")
                        .HasForeignKey("JudicialProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_judicial_process");

                    b.HasOne("processum.Models.StatusPayment", "StatusPayment")
                        .WithMany("LegalFees")
                        .HasForeignKey("StatusPaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_status_payment");

                    b.HasOne("processum.Models.User", "User")
                        .WithMany("LegalFees")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_id");

                    b.Navigation("JudicialProcess");

                    b.Navigation("StatusPayment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("processum.Models.LegalFeeEntity", b =>
                {
                    b.HasOne("processum.Models.Entity", "Entity")
                        .WithMany("LegalFeeEntities")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_legal_fee_entity_entity");

                    b.HasOne("processum.Models.LegalFee", "LegalFee")
                        .WithMany("LegalFeeEntities")
                        .HasForeignKey("LegalFeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_legal_fee_entity_legal_fee");

                    b.Navigation("Entity");

                    b.Navigation("LegalFee");
                });

            modelBuilder.Entity("processum.Models.LegalFeesInstallment", b =>
                {
                    b.HasOne("processum.Models.Entity", "Entity")
                        .WithMany("LegalFeesInstallments")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_legal_fee_entity");

                    b.HasOne("processum.Models.StatusPayment", "StatusPayment")
                        .WithMany("LegalFeesInstallments")
                        .HasForeignKey("StatusPaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_status_payment");

                    b.Navigation("Entity");

                    b.Navigation("StatusPayment");
                });

            modelBuilder.Entity("processum.Models.Settlement", b =>
                {
                    b.HasOne("processum.Models.JudicialProcess", "JudicialProcess")
                        .WithMany("Settlements")
                        .HasForeignKey("JudicialProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_judicial_process");

                    b.HasOne("processum.Models.StatusPayment", "StatusPayment")
                        .WithMany("Settlements")
                        .HasForeignKey("StatusPaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_status_payment");

                    b.HasOne("processum.Models.User", "User")
                        .WithMany("Settlements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_id");

                    b.Navigation("JudicialProcess");

                    b.Navigation("StatusPayment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("processum.Models.EntitiesRole", b =>
                {
                    b.Navigation("EntitiesRolesMaps");
                });

            modelBuilder.Entity("processum.Models.Entity", b =>
                {
                    b.Navigation("EntityCompany");

                    b.Navigation("EntityIndividual");

                    b.Navigation("JudicialProcessEntities");

                    b.Navigation("LegalFeeEntities");

                    b.Navigation("LegalFeesInstallments");
                });

            modelBuilder.Entity("processum.Models.JudicialProcess", b =>
                {
                    b.Navigation("JudicialProcessEntities");

                    b.Navigation("LegalFees");

                    b.Navigation("Settlements");
                });

            modelBuilder.Entity("processum.Models.LegalFee", b =>
                {
                    b.Navigation("LegalFeeEntities");
                });

            modelBuilder.Entity("processum.Models.NatureAction", b =>
                {
                    b.Navigation("JudicialAction");

                    b.Navigation("JudicialProcesses");
                });

            modelBuilder.Entity("processum.Models.StatusPayment", b =>
                {
                    b.Navigation("LegalFees");

                    b.Navigation("LegalFeesInstallments");

                    b.Navigation("Settlements");
                });

            modelBuilder.Entity("processum.Models.User", b =>
                {
                    b.Navigation("Clients");

                    b.Navigation("JudicialProcessUsers");

                    b.Navigation("JudicialProcesses");

                    b.Navigation("LegalFees");

                    b.Navigation("Settlements");
                });
#pragma warning restore 612, 618
        }
    }
}
